#!/bin/bash
set -euo pipefail

cargo metadata --format-version 1 |
  jq -r '
    .workspace_members as $ws |
    .packages[] | select(.id as $id | $ws | contains([$id])) |
    .targets[] | select(.kind == ["bin"]) |
    .name
  '
