[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
garde = "0.20"
k8s-openapi = { version = "0.22", features = ["latest"] }
kube = "0.93"
schemars = "0.8"
serde = "1"
serde_json = "1"
thiserror = "1"
tokio = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
