[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
k8s-openapi = { version = "0.22", features = ["latest"] }
kube = "0.93"
tokio = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
